[package]
name = "rsiotmonitor"
version = "0.1.0"
edition = "2021"

[dependencies]

chrono = "^0.4.23"

env_logger = "0.11"
log = "0.4.8"

# bytes = "0.4.0"
futures-core = "0.3.1"
futures-util = "0.3.1"

nix = { version= "0.29", features=["signal"]}

maplit = "1.0.2"
mqtt-async-client = { path = "deps/mqtt-async-client-rs" }

rustls = { version = "0.23", optional = true }
rustls-pemfile = { version = "2.2", optional = true }
webpki-roots = "0.26"

structopt = "0.3.5"

tokio = { version = "1.37.0", features = ["io-util", "macros", "net", "rt", "process", "rt-multi-thread", "sync", "time"] }
tokio-rustls = { version = "0.26", optional = true }

toml-parse = { path="deps/toml-parse" }

sqlite="0.36.2"

derivative = "2.2.0"
mqtt-v5-broker = { path = "deps/mqtt-broker/mqtt-v5-broker" }

actix-web = "4"
actix-cors = "0.7"
async-stream = "0.3.5"

serde = { version = "1.0" }
serde_json = { version = "1.0" }

derive_more = "0.99.17"


rs-leveldb = { path = "deps/leveldb" }
db-key = "0.0.5"

mlua = { version = "0.10", features = ["lua54", "vendored"] }

parquet="57.1.0"

tokio-cron-scheduler = "0.13"

# arrow-flight = "51.0.0"
# futures = { version = "0.3", default-features = false, features = ["alloc"] }
# tonic = { version = "0.11.0", default-features = false, features = ["transport", "codegen", "prost"] }

datafusion = "51.0"
datafusion-physical-expr = "51.0"
datafusion-expr = "51.0"
arrow = "57.1"

async-trait = "0.1.73"

[features]
default = ["tls"]
tls = ["rustls", "tokio-rustls", "rustls-pemfile"]

[profile.release]
opt-level = "z"  # Optimize for size.
codegen-units = 1
panic = "abort"
lto = true

[dependencies.sqlite3-src]
version="0.6.1"     
features=["bundled"]

